export const CREATE_REQUEST_TOKEN_URL = '/authentication/token/new'
export const CREATE_SESSION_URL = '/authentication/session/new'
export const VALIDATE_WITH_LOGIN_URL = '/authentication/token/validate_with_login'
export const CREATE_GUEST_SESSION_URL = '/authentication/guest_session/new'
export const ACCOUNT_URL = '/account'
